[package]
name = "automata"
version = "0.0.0"
edition = "2024"

[dependencies]
derivative = "2.2.0"
freedesktop-desktop-entry = "0.7.19"
gtk4 = "0.10.1"
logind-zbus = "5.3.2"
rust-ini = "0.21.3"
xdg-utils = "0.4.0"
zbus = { version = "5.7.0", default-features = false }

